version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - gamoutatsumi
    target-branch: "feature"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: daily
    labels:
      - dependencies
      - automerge
